name: hello-world

on: push 
jobs: 
  hello-world-jobs: 
     runs-on: ubuntu-latest 
     steps: 
       - name: checkout repo code 
         uses: actions/checkout@v4
       - run: echo "hello world print"  
